name       : zotero
version    : 5.0.34.4
release    : 1
source     :
       - test|file:///home/ivanhoe1024/Build/zotero-5.0.34.4.tar.gz : 74489148d9126fb3a455ad9a9e8ddaf0e1917d7456766f0183467b1a47bc65af
       - file:///home/ivanhoe1024/Build/zotero-standalone-build-5.0.34.4.tar.gz : 38818b1dc24721599d092b5ae31dc80e7eb633a89c3621c6ea5ad4769c27e5e2
license    : AGPL-3.0
component  : office.scientific
summary    : Free, easy-to-use tool to help you collect, organize, cite, and share your research sources
description: |
    Free, easy-to-use tool to help you collect, organize, cite, and share your research sources
networking : yes
builddeps  :
    - curl
    - gawk
    - git
    - nodejs
    - perl
    - python
    - python3
    - rsync
    - wget
rundeps    : 
    - dbus-glib
    - libgtk-2
    - libgtk-3
    - libnss
    - libxt
setup      : |
    tar -xvf $sources/zotero-standalone-build-$version.tar.gz -C $workdir/../.
    ln -s $workdir $workdir/../zotero-client
    cd $workdir/..
    git clone --recursive https://github.com/zotero/zotero-build
    cd $workdir/../zotero-standalone-build-$version
    %patch -p0 < $pkgfiles/0001-5.0_release_build_and_deploy.patch
    %patch -p0 < $pkgfiles/0002-build_and_deploy.patch
    %patch -p0 < $pkgfiles/0003-make_full_update.patch
build      : |
    npm i
    npm run build
    cd ../zotero-standalone-build-$version
    #script/check_requirements
    ./fetch_xulrunner.sh -p l
    #./fetch_pdftools
    #scripts/dir_build -p l
    scripts/5.0_release_build_and_deploy
install    : |
    #install actual files
    #install -dDm00755 $installdir/usr/bin
    #install -dDm00755 $installdir/usr/share/zotero
    mv $workdir/../zotero-standalone-build-$version/staging/Zotero_linux-x86_64/* $installdir/usr/share/zotero/.
    ln -s /usr/share/zotero/zotero $installdir/usr/bin/zotero
    #disable APP autoupdate
    sed -i '/pref("app.update.enabled", true);/c\pref("app.update.enabled", false);' $installdir/usr/share/zotero/defaults/preferences/prefs.js
    #install .desktop file
    rm $installdir/usr/share/zotero/zotero.desktop
    install -Dm00644 $pkgfiles/zotero.desktop $installdir/usr/share/applications/zotero.desktop
    #install icons
    install -Dm00644 $installdir/usr/share/zotero/chrome/icons/default/default16.png $installdir/usr/share/icons/hicolor/16x16/apps/zotero.png
    install -Dm00644 $installdir/usr/share/zotero/chrome/icons/default/default32.png $installdir/usr/share/icons/hicolor/32x32/apps/zotero.png
    install -Dm00644 $installdir/usr/share/zotero/chrome/icons/default/default48.png $installdir/usr/share/icons/hicolor/48x48/apps/zotero.png
    install -Dm00644 $installdir/usr/share/zotero/chrome/icons/default/default256.png $installdir/usr/share/icons/hicolor/256x256/apps/zotero.png
    
